### ISSUE TITLE
Exported file contain all unused data-blocks from source 

### ISSUE THREAD

**Issue by Nicknroll** [CGCookie/io_export_blend#6]
Hi, thanks a lot, really useful add-on, finally i can replace heavy objects with a link in a fast way!

But first thing i noticed that exported file has a weight of the source file, so i found it contain all unused data-blocks.
Probably you need to add something like auto-purge.

Also, it would be just awesome if you make possible to export material as asset :) 

Regards
Nick

**Comment by ZanQdo** [comment]
+1 on this. If you go to the Blender File outliner mode it will show ALL data same as the source

**Comment by Fweeb** [comment]
Apologies for the [very] late response. It seems this issue is even more acute in Blender 3.1.

Investigating now.

**Comment by Fweeb** [comment]
This should be handled now. Grab v1.1 and you should see happier results.
